export const countryCodes = [
    { code: '+1', name: 'United States' },
    { code: '+44', name: 'United Kingdom' },
    { code: '+91', name: 'India' },
    {code: '+86', name:'Chine'},
    {code: '+33', name:'France'},
    {code: '+48', name:'Poland'},
    {code: '+880', name:'Bangladesh'},
    {code: '+61', name:'Australia'},
    {code: '+43', name:'Austria'},
    {code: '+90', name:'Turkey'},
    {code: '+380', name:'Ukraine'},
    {code: '+970', name:'Palestine'},
    {code: '+351', name:'Portugal'},
    {code: '+7', name:'Russia'},
    {code: '+34', name:'Spain'},
    {code: '+94', name:'Sri Lanka'},
    {code: '+27', name:'South Africa'},
];