export const countryCodes = [
    { code: '+1', name: 'United States', countryCode:"US" },
    { code: '+44', name: 'United Kingdom', countryCode:"GB" },
    { code: '+91', name: 'India', countryCode:"IN" },
    {code: '+86', name:'China', countryCode:"CN"},
    {code: '+33', name:'France', countryCode:"FR"},
    {code: '+48', name:'Poland', countryCode:"PL"},
    {code: '+880', name:'Bangladesh', countryCode:"BD"},
    {code: '+61', name:'Australia', countryCode:"AU"},
    {code: '+43', name:'Austria', countryCode:"AT"},
    {code: '+90', name:'Turkey', countryCode:"TR"},
    {code: '+380', name:'Ukraine', countryCode:"UA"},
    {code: '+970', name:'Palestine', countryCode:"PS"},
    {code: '+351', name:'Portugal', countryCode:"PT"},
    {code: '+7', name:'Russia', countryCode:"RU"},
    {code: '+34', name:'Spain', countryCode:"ES"},
    {code: '+94', name:'Sri Lanka', countryCode:"LK"},
    {code: '+27', name:'South Africa', countryCode:"ZA"},
];